site_name: HyperDex Software Stack
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    primary: black
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.select
  font:
    text: Roboto

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition

nav:
  - Getting Started:
    - Installation Guide: install_guide.md
    - Quick Start with vLLM(WIP): vllm_python.md
    - Quick Start with HuggingFace: quick_start.md
  - Software: 
    - About HyperDex:
      - HyperDex SDK: hyperdex_sdk.md
      - Supported Models: supported_models.md
    - API:
      - vLLM API(WIP): vllm_api.md
      - HuggingFace API(WIP): huggingface_api.md
      - OpenAI API(WIP): openai_api.md
    - Serving:
      - Deploying with Docker: docker.md
      - Serving With vLLM(WIP): vllm_serving.md
      - Serving With OpenAI(WIP): openai_serving.md
      - Serving with TGI: serving.md
      - Serving with ChatUI: chatui.md
  - About LPU:
    - Performance:
      - LPU Performance(WIP): lpu_performance.md
      - Hybrid Performance(WIP): hybrid_performance.md
    - Q&A: 
      - Troubleshooting(Prev): troubleshooting.md 
      - About Server: Q_server.md
      - About Device: Q_device.md
      - About Software: Q_software.md

copyright: Copyright &copy; 2023 - 2024 HyperAccel Inc.
extra:
  generator: false
