site_name: HyperAccel Documents

theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md
  - Getting Started : guide.md 
  - Models: models.md
  - Compilation: compile.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences