site_name: HyperAccel Documents

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python

nav:
  - Home: index.md
  - Getting Started : guide.md 
  - Models: models.md
  - Compilation: compile.md
