
site_name: HyperAccel Documents

theme:
  name: readthedocs

nav:
  - Getting Started: 
    - Quick Start: index.md
    - HyperDex-Python: guide.md
    - HyperDex-Serve: serve.md
  - Models:
    - LLM Compile: compile.md
    - Supported Models: models.md
  - Demos:
    - HyperAccel Chatbot: chatui.md

